
tasks:
  - name: "Run the container"
    command: docker run --name yottadb --entrypoint /home/gocode/entrypoint.sh -it -v $PWD/code:/home/gocode docker.io/yottadb/yottadb-base

  - name: "Run YottaDB prompt"
    command:  sleep 60 && docker exec -it yottadb /opt/yottadb/current/ydb
    openMode: split-right

  - name: "Run command line"
    command:  sleep 60 && docker exec -it yottadb bash -c "source /opt/yottadb/current/ydb_env_set && export PATH=$PATH:/usr/local/go/bin && cd /home/gocode && bash"
    openMode: split-right



